from __future__ import annotations
import hashlib,json,os,tomllib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; data=ROOT/'data/personalbench_x.jsonl'
if not data.exists(): raise SystemExit('Missing data/personalbench_x.jsonl; run export_belief_dataset.py first')
version=tomllib.loads((ROOT/'pyproject.toml').read_text())['project']['version']; sha=hashlib.sha256(data.read_bytes()).hexdigest(); rows=sum(1 for _ in data.open())
url=os.environ.get('PERSONALBENCH_X_DATASET_URL','REPLACE_WITH_ANONYMOUS_REVIEW_URL_BEFORE_SUBMISSION')
ctx={
 '@language':'en','@vocab':'https://schema.org/','sc':'https://schema.org/','cr':'http://mlcommons.org/croissant/','rai':'http://mlcommons.org/croissant/RAI/','prov':'http://www.w3.org/ns/prov#','dct':'http://purl.org/dc/terms/','conformsTo':'dct:conformsTo','field':'cr:field','source':'cr:source','fileObject':'cr:fileObject','extract':'cr:extract','jsonPath':'cr:jsonPath','dataType':{'@id':'cr:dataType','@type':'@vocab'}
}
def field(name,dtype='sc:Text',desc=''):
 return {'@type':'cr:Field','@id':f'users/{name}','name':name,'description':desc,'dataType':dtype,'source':{'fileObject':{'@id':'personalbench-x-jsonl'},'extract':{'jsonPath':f'$.{name}'}}}
obj={
 '@context':ctx,'@type':'sc:Dataset','name':'PersonaMetrica-Bench','description':'Controlled synthetic benchmark for belief updating and decision risk under evolving personal preferences.','version':version,'datePublished':'2026-09-24','url':url,'license':'https://opensource.org/license/mit','conformsTo':'http://mlcommons.org/croissant/1.1',
 'distribution':[{'@type':'cr:FileObject','@id':'personalbench-x-jsonl','name':'personalbench_x.jsonl','contentUrl':'data/personalbench_x.jsonl','sha256':sha,'encodingFormat':'application/x-ndjson'}],
 'recordSet':[{'@type':'cr:RecordSet','@id':'users','name':'users','description':'One record per synthetic user, containing the complete structured observation and decision-query trajectory.','field':[field('user_id','sc:Text','Synthetic user identifier.'),field('turns','sc:Integer','Configured history length in turns.'),field('observations','sc:Text','JSON array of structured evidence observations.'),field('queries','sc:Text','JSON array of decision queries and simulator reference states.')]}],
 'recordCount':rows,
 'rai:dataLimitations':'Synthetic structured evidence; binary preference domains; generator-defined transition dynamics; not validated for natural-language extraction, real human populations, or frontier-model performance. Not recommended as the sole evidence for deployment decisions.',
 'rai:dataBiases':'Domain selection, source reliabilities, temporal processes, and query schedules are designed by the benchmark authors and may overrepresent cleanly factorized preference dynamics compared with natural interaction.',
 'rai:personalSensitiveInformation':'No real-person data, demographic attributes, medical records, political/religious beliefs, or direct identifiers are included. User identifiers are synthetic.',
 'rai:dataUseCases':'Established use: controlled evaluation of state tracking, calibration, risk-coverage, and decision utility under known evolving preferences. Not established: natural-language understanding, human-population validity, fairness, production safety, or real-user personalization quality.',
 'rai:dataSocialImpact':'Potential positive use includes more rigorous evaluation of personal-agent memory and uncertainty. Misuse could encourage persistent profiling or overconfident automated action if synthetic results are overgeneralized; the release therefore documents limitations and emphasizes calibration, user control, and permission boundaries.',
 'rai:hasSyntheticData':True,
 'prov:wasGeneratedBy':{'@type':'prov:Activity','name':'PersonaMetrica-Bench deterministic generator','description':'Generated by personalbench/belief_benchmark.py using fixed seeds. Standard release uses seed 31; development and held-out seed ranges are documented in the paper.'}
}
payload=json.dumps(obj,indent=2,ensure_ascii=False)+'\n'
(ROOT/'data/personalbench_x_croissant.json').write_text(payload)
(ROOT/'data/personametrica_bench_croissant.json').write_text(payload)
print(f'Wrote PersonaMetrica-Bench Croissant 1.1 metadata: {rows} user records; version={version}; sha256={sha}; url={url}')
