from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
d=json.loads((ROOT/'data/eval_results.json').read_text())
s=d['systems']; f=s['full_temporal_os']['metrics']

adv=f'''# Adversarial Language Evaluation\n\nThis report evaluates the transparent local preference estimator on language forms that are intentionally more varied than the main simulator templates. It is a stress test of parsing and temporal slot continuity, not a claim of general natural-language understanding.\n\n## Results\n\n- Preference-language stress accuracy: **{100*f['language_stress_accuracy']:.1f}%**\n- Stress-suite Brier error: **{f['language_stress_brier']:.4f}**\n- Multi-turn reversal-sequence accuracy: **{100*f['reversal_sequence_accuracy']:.1f}%**\n\nThe suite includes explicit preferences, hedges, within-utterance reversals (`used to ... but now ...`), elliptical multi-turn updates, conditional technical-detail preferences, likes, and dislikes.\n\n## Known failure surface\n\nThe local estimator remains pattern-based. Unsupported paraphrases, implicit preferences requiring pragmatic inference, multilingual utterances, and references requiring world knowledge are intentionally outside the evidence boundary. A learned extractor should be evaluated against this same interface before any stronger claim is made.\n'''
(ROOT/'reports/ADVERSARIAL_EVAL.md').write_text(adv)

privacy=s['no_privacy_guard']['metrics']
pr=f'''# Privacy and User-Control Evaluation\n\nPersonalization should not imply indiscriminate retention. The local system therefore contains a conservative persistence guard for obvious secrets plus explicit forgetting and an append-only audit trail for memory lifecycle events.\n\n## Controlled results\n\n- Safe ordinary-memory recall: **{100*f['privacy_safe_memory_recall']:.1f}%**\n- Sensitive-memory block rate: **{100*f['privacy_sensitive_block_rate']:.1f}%**\n- Without the privacy guard: **{100*privacy['privacy_sensitive_block_rate']:.1f}%** block rate\n- Explicit forget success: **{100*f['forget_success_rate']:.1f}%**\n- Deleted-memory retrieval rate: **{100*f['deleted_memory_retrieval_rate']:.1f}%**\n- Memory audit coverage: **{100*f['memory_audit_coverage']:.1f}%**\n\n## Scope boundary\n\nThe privacy guard detects a narrow set of obvious credential, financial, and government-ID phrases. It is not a production PII classifier and does not replace encryption, authorization, retention policy, data residency controls, or consent UX. Its purpose is to make persistence policy explicit and ablatable in the research substrate.\n'''
(ROOT/'reports/PRIVACY_USER_CONTROL.md').write_text(pr)

ledger='''# Evidence Ledger\n\n| Claim | Executable evidence | Boundary |\n|---|---|---|\n| Temporal updates reduce stale personal state | `no_temporal_update` ablation, multi-seed paired effects | Synthetic preference-drift personas |\n| Conflict resolution prevents simultaneously active contradictory state | `no_contradiction_resolution` ablation | Canonical structured slots |\n| Calibrated proactivity improves the benchmark oracle and high-stakes confirmation behavior | 200-scenario eval + 1,000-scenario failure slices | Hand-authored normative oracle, not human preference |\n| Outcome verification catches injected execution mismatch | verifier ablation | Deterministic sandbox tools |\n| Explicit forgetting removes memory from active retrieval | user-control benchmark + unit tests | Local in-memory backend |\n| Obvious secrets can be blocked from persistent memory | privacy-guard ablation | Narrow regex categories, not general PII detection |\n| State survives process/session boundaries | schema-versioned snapshot round-trip tests | Local JSON; no production encryption/auth |\n| Feedback and tool-world state survive snapshot restore | v2 persistence integration test | Sandbox-only tools |\n| Estimator handles several adversarial temporal phrasings | adversarial language suite | Pattern-based English stress set |\n| Repository is reproducible | one-command reproduction, manifest, release check | Tested in local Python environment |\n\nNo entry in this ledger claims a completed human longitudinal study, frontier-model post-training result, or production deployment.\n'''
(ROOT/'docs/EVIDENCE_LEDGER.md').write_text(ledger)
print('extended reports built')
